#ifndef __ExplicitInstantiation_itkQuadEdgeMeshPolygonCell_h__
#define __ExplicitInstantiation_itkQuadEdgeMeshPolygonCell_h__
//exclude QuadEdgeMeshPolygonCell
#endif //__ExplicitInstantiation_itkQuadEdgeMeshPolygonCell_h__
