#ifndef __ExplicitInstantiation_itkQuadEdgeMeshLineCell_h__
#define __ExplicitInstantiation_itkQuadEdgeMeshLineCell_h__
//exclude QuadEdgeMeshCellTraitsInfo
#endif //__ExplicitInstantiation_itkQuadEdgeMeshLineCell_h__
