#ifndef __ExplicitInstantiation_itkQuadEdgeMeshLineCell_h__
#define __ExplicitInstantiation_itkQuadEdgeMeshLineCell_h__
extern template class itk::QuadEdgeMeshLineCell<itk::CellInterface<double, itk::QuadEdgeMeshCellTraitsInfo<3, float, float, unsigned long, unsigned long, unsigned char, itk::QuadEdgeMeshPoint<float, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> >, itk::MapContainer<unsigned long, itk::QuadEdgeMeshPoint<float, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > >, std::__1::set<unsigned long, std::__1::less<unsigned long>, std::__1::allocator<unsigned long> >, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > > >;
extern template class itk::QuadEdgeMeshLineCell<itk::CellInterface<float, itk::QuadEdgeMeshCellTraitsInfo<3, float, float, unsigned long, unsigned long, unsigned char, itk::QuadEdgeMeshPoint<float, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> >, itk::MapContainer<unsigned long, itk::QuadEdgeMeshPoint<float, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > >, std::__1::set<unsigned long, std::__1::less<unsigned long>, std::__1::allocator<unsigned long> >, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > > >;
extern template class itk::QuadEdgeMeshLineCell<itk::CellInterface<double, itk::QuadEdgeMeshCellTraitsInfo<3, double, double, unsigned long, unsigned long, unsigned long, itk::QuadEdgeMeshPoint<double, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> >, itk::MapContainer<unsigned long, itk::QuadEdgeMeshPoint<double, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > >, std::__1::set<unsigned long, std::__1::less<unsigned long>, std::__1::allocator<unsigned long> >, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > > >;
extern template class itk::QuadEdgeMeshLineCell<itk::CellInterface<itk::Vector<double, 3u>, itk::QuadEdgeMeshCellTraitsInfo<3, double, double, unsigned long, unsigned long, unsigned long, itk::QuadEdgeMeshPoint<double, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> >, itk::MapContainer<unsigned long, itk::QuadEdgeMeshPoint<double, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > >, std::__1::set<unsigned long, std::__1::less<unsigned long>, std::__1::allocator<unsigned long> >, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > > >;
extern template class itk::QuadEdgeMeshLineCell<itk::CellInterface<int, itk::QuadEdgeMeshCellTraitsInfo<3, float, float, unsigned long, unsigned long, unsigned char, itk::QuadEdgeMeshPoint<float, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> >, itk::MapContainer<unsigned long, itk::QuadEdgeMeshPoint<float, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > >, std::__1::set<unsigned long, std::__1::less<unsigned long>, std::__1::allocator<unsigned long> >, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > > >;
extern template class itk::QuadEdgeMeshLineCell<itk::CellInterface<itk::CovariantVector<float, 3u>, itk::QuadEdgeMeshCellTraitsInfo<3, float, float, unsigned long, unsigned long, unsigned char, itk::QuadEdgeMeshPoint<float, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> >, itk::MapContainer<unsigned long, itk::QuadEdgeMeshPoint<float, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > >, std::__1::set<unsigned long, std::__1::less<unsigned long>, std::__1::allocator<unsigned long> >, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > > >;
extern template class itk::QuadEdgeMeshLineCell<itk::CellInterface<float, itk::QuadEdgeMeshCellTraitsInfo<3, double, double, unsigned long, unsigned long, unsigned long, itk::QuadEdgeMeshPoint<double, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> >, itk::MapContainer<unsigned long, itk::QuadEdgeMeshPoint<double, 3u, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > >, std::__1::set<unsigned long, std::__1::less<unsigned long>, std::__1::allocator<unsigned long> >, itk::GeometricalQuadEdge<unsigned long, unsigned long, bool, bool, true> > > >;
#endif //__ExplicitInstantiation_itkQuadEdgeMeshLineCell_h__