#ifndef __ExplicitInstantiation_itkQuadEdgeMeshEulerOperatorCreateCenterVertexFunction_h__
#define __ExplicitInstantiation_itkQuadEdgeMeshEulerOperatorCreateCenterVertexFunction_h__
//exclude QuadEdgeMesh
#endif //__ExplicitInstantiation_itkQuadEdgeMeshEulerOperatorCreateCenterVertexFunction_h__