#ifndef __ExplicitInstantiation_itkImageFunction_h__
#define __ExplicitInstantiation_itkImageFunction_h__
#include "itkImage.h"
#include "itkVectorImage.h"
extern template class itk::ImageFunction<itk::Image<itk::Vector<double, 2u>, 3u>, itk::Vector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 1u>, 2u>, itk::Matrix<double, 1u, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<itk::FixedArray<float, 2u>, 2u>, itk::FixedArray<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<itk::FixedArray<float, 3u>, 3u>, itk::FixedArray<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<float, 4u>, double, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 4u>, 2u>, itk::Matrix<double, 4u, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<float, 3u>, double, double>;
extern template class itk::ImageFunction<itk::Image<double, 2u>, double, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 2u>, 2u>, itk::Vector<double, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 2u>, 2u>, itk::Matrix<double, 2u, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 3u>, 2u>, itk::Vector<double, 3u>, float>;
extern template class itk::ImageFunction<itk::Image<float, 2u>, bool, float>;
extern template class itk::ImageFunction<itk::Image<float, 3u>, float, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 5u>, 2u>, itk::Vector<double, 5u>, float>;
extern template class itk::ImageFunction<itk::Image<itk::FixedArray<unsigned char, 4u>, 3u>, vnl_matrix<double>, float>;
extern template class itk::ImageFunction<itk::VectorImage<float, 2u>, itk::VariableLengthVector<double>, float>;
extern template class itk::ImageFunction<itk::Image<unsigned int, 2u>, double, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<unsigned short, 3u>, 3u>, itk::Vector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<double, 1u>, double, double>;
extern template class itk::ImageFunction<itk::Image<unsigned int, 2u>, double, double>;
extern template class itk::ImageFunction<itk::Image<itk::CovariantVector<double, 2u>, 2u>, itk::CovariantVector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 2u>, bool, double>;
extern template class itk::ImageFunction<itk::Image<short, 3u>, itk::CovariantVector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<unsigned short, 2u>, double, double>;
extern template class itk::ImageFunction<itk::Image<unsigned int, 2u>, itk::CovariantVector<double, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<float, 2u>, float, float>;
extern template class itk::ImageFunction<itk::Image<float, 3u>, itk::CovariantVector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 3u>, itk::CovariantVector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<itk::RGBPixel<unsigned char>, 2u>, itk::RGBPixel<double>, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<double, 1u>, 1u>, itk::Vector<double, 1u>, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<double, 3u>, 3u>, itk::Vector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<char, 3u>, double, double>;
extern template class itk::ImageFunction<itk::Image<itk::RGBPixel<unsigned char>, 2u>, itk::RGBPixel<double>, double>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 2u>, double, float>;
extern template class itk::ImageFunction<itk::Image<double, 2u>, double, float>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 3u>, double, float>;
extern template class itk::ImageFunction<itk::Image<itk::RGBPixel<unsigned char>, 2u>, bool, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 6u>, 2u>, itk::Matrix<double, 6u, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 3u>, itk::CovariantVector<double, 3u>, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 3u>, 3u>, itk::Vector<double, 3u>, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 4u>, 2u>, itk::Vector<double, 4u>, float>;
extern template class itk::ImageFunction<itk::Image<short, 2u>, double, double>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 3u>, double, double>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 2u>, itk::CovariantVector<double, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<unsigned int, 2u>, itk::CovariantVector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<itk::CovariantVector<double, 3u>, 3u>, itk::CovariantVector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 2u>, 2u>, itk::Vector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<double, 2u>, itk::CovariantVector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 6u>, 2u>, itk::Vector<double, 6u>, float>;
extern template class itk::ImageFunction<itk::Image<float, 3u>, double, float>;
extern template class itk::ImageFunction<itk::Image<float, 2u>, double, double>;
extern template class itk::ImageFunction<itk::Image<float, 2u>, itk::CovariantVector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 2u>, double, double>;
extern template class itk::ImageFunction<itk::Image<itk::RGBPixel<unsigned char>, 2u>, vnl_matrix<double>, float>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 2u>, bool, float>;
extern template class itk::ImageFunction<itk::Image<float, 1u>, double, float>;
extern template class itk::ImageFunction<itk::Image<unsigned short, 2u>, itk::CovariantVector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<unsigned short, 3u>, double, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<double, 2u>, 2u>, itk::Vector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<unsigned char, 2u>, itk::CovariantVector<double, 2u>, double>;
extern template class itk::ImageFunction<itk::Image<double, 3u>, double, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 3u>, 2u>, itk::Matrix<double, 3u, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<short, 3u>, double, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 3u>, 3u>, itk::Vector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<float, 2u>, double, float>;
extern template class itk::ImageFunction<itk::Image<float, 2u>, bool, double>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 1u>, 2u>, itk::Vector<double, 1u>, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<float, 5u>, 2u>, itk::Matrix<double, 5u, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<double, 3u>, itk::CovariantVector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<float, 2u>, itk::CovariantVector<double, 2u>, float>;
extern template class itk::ImageFunction<itk::Image<itk::Vector<double, 3u>, 4u>, itk::Vector<double, 3u>, double>;
extern template class itk::ImageFunction<itk::Image<char, 3u>, itk::CovariantVector<double, 3u>, double>;
#endif //__ExplicitInstantiation_itkImageFunction_h__
