#ifndef __ExplicitInstantiation_itkBoxSpatialObject_h__
#define __ExplicitInstantiation_itkBoxSpatialObject_h__
extern template class itk::BoxSpatialObject<2u>;
#endif //__ExplicitInstantiation_itkBoxSpatialObject_h__