#ifndef __ExplicitInstantiation_itkDTITubeSpatialObjectPoint_h__
#define __ExplicitInstantiation_itkDTITubeSpatialObjectPoint_h__
extern template class itk::DTITubeSpatialObjectPoint<3u>;
extern template class itk::DTITubeSpatialObjectPoint<2u>;
#endif //__ExplicitInstantiation_itkDTITubeSpatialObjectPoint_h__