#ifndef __ExplicitInstantiation_itkDTITubeSpatialObject_h__
#define __ExplicitInstantiation_itkDTITubeSpatialObject_h__
extern template class itk::DTITubeSpatialObject<3u>;
extern template class itk::DTITubeSpatialObject<2u>;
#endif //__ExplicitInstantiation_itkDTITubeSpatialObject_h__