#ifndef __ExplicitInstantiation_itkLineSpatialObjectPoint_h__
#define __ExplicitInstantiation_itkLineSpatialObjectPoint_h__
extern template class itk::LineSpatialObjectPoint<2u>;
extern template class itk::LineSpatialObjectPoint<3u>;
#endif //__ExplicitInstantiation_itkLineSpatialObjectPoint_h__