#ifndef __ExplicitInstantiation_itkPolygonSpatialObject_h__
#define __ExplicitInstantiation_itkPolygonSpatialObject_h__
extern template class itk::PolygonSpatialObject<3u>;
#endif //__ExplicitInstantiation_itkPolygonSpatialObject_h__