#ifndef __ExplicitInstantiation_itkTubeSpatialObjectPoint_h__
#define __ExplicitInstantiation_itkTubeSpatialObjectPoint_h__
extern template class itk::TubeSpatialObjectPoint<2u>;
extern template class itk::TubeSpatialObjectPoint<3u>;
#endif //__ExplicitInstantiation_itkTubeSpatialObjectPoint_h__