#ifndef __ExplicitInstantiation_itkDiscreteHessianGaussianImageFunction_h__
#define __ExplicitInstantiation_itkDiscreteHessianGaussianImageFunction_h__
extern template class itk::DiscreteHessianGaussianImageFunction<itk::Image<float, 3u>, float>;
#endif //__ExplicitInstantiation_itkDiscreteHessianGaussianImageFunction_h__