#ifndef __ExplicitInstantiation_itkStatisticsRelabelLabelMapFilter_h__
#define __ExplicitInstantiation_itkStatisticsRelabelLabelMapFilter_h__
extern template class itk::StatisticsRelabelLabelMapFilter<itk::LabelMap<itk::StatisticsLabelObject<unsigned char, 2u> > >;
#endif //__ExplicitInstantiation_itkStatisticsRelabelLabelMapFilter_h__