#ifndef __ExplicitInstantiation_itkFloodFilledSpatialFunctionConditionalConstIterator_h__
#define __ExplicitInstantiation_itkFloodFilledSpatialFunctionConditionalConstIterator_h__
//exclude EllipseSpatialObject
#endif //__ExplicitInstantiation_itkFloodFilledSpatialFunctionConditionalConstIterator_h__