#ifndef __ExplicitInstantiation_itkFloodFilledImageFunctionConditionalIterator_h__
#define __ExplicitInstantiation_itkFloodFilledImageFunctionConditionalIterator_h__
//exclude BinaryThresholdImageFunction
//exclude MahalanobisDistanceThresholdImageFunction
#endif //__ExplicitInstantiation_itkFloodFilledImageFunctionConditionalIterator_h__