#ifndef __ExplicitInstantiation_itkImageKernelOperator_h__
#define __ExplicitInstantiation_itkImageKernelOperator_h__
//exclude NeighborhoodAllocator
#endif //__ExplicitInstantiation_itkImageKernelOperator_h__