#ifndef __ExplicitInstantiation_itkImageScanlineIterator_h__
#define __ExplicitInstantiation_itkImageScanlineIterator_h__
//exclude VectorImage
//subs std::__1 std::
extern template class itk::ImageScanlineIterator<itk::Image<short, 4u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<float, 1u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned char, 4u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::RGBPixel<unsigned char>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<short, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<char, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<std::complex<double>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::FixedArray<float, 3u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<double, 3u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<double, 2u>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::CovariantVector<double, 3u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned short, 4u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned long long, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::RGBPixel<float>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<double, 4u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Offset<2u>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<double, 3u>, 4u> >;
extern template class itk::ImageScanlineIterator<itk::Image<int, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<float, 2u>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<double, 2u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned int, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned long, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::RGBAPixel<unsigned char>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned char, 1u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::SymmetricSecondRankTensor<double, 3u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned int, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<double, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<float, 4u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned short, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::CovariantVector<double, 2u>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<int, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::DiffusionTensor3D<float>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<float, 3u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::FixedArray<float, 2u>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::RGBAPixel<unsigned char>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<float, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<double, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<unsigned char, 2u>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<long, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<float, 4u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<short, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned char, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::CovariantVector<float, 2u>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<long long, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::FixedArray<double, 3u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::DiffusionTensor3D<float>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned long, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::RGBAPixel<float>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::RGBPixel<short>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<float, 6u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::RGBPixel<unsigned char>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Matrix<float, 3u, 3u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<float, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<char, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<float, 3u>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::RGBPixel<unsigned short>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::DiffusionTensor3D<double>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned char, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::CovariantVector<float, 3u>, 3u> >;
extern template class itk::ImageScanlineIterator<itk::Image<std::complex<float>, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<unsigned short, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<long, 2u> >;
extern template class itk::ImageScanlineIterator<itk::Image<itk::Vector<float, 1u>, 2u> >;
#endif //__ExplicitInstantiation_itkImageScanlineIterator_h__