#ifndef __ExplicitInstantiation_itkImageRegionReverseIterator_h__
#define __ExplicitInstantiation_itkImageRegionReverseIterator_h__
extern template class itk::ImageRegionReverseIterator<itk::Image<double, 2u> >;
#endif //__ExplicitInstantiation_itkImageRegionReverseIterator_h__