#ifndef __ExplicitInstantiation_itkPreOrderTreeIterator_h__
#define __ExplicitInstantiation_itkPreOrderTreeIterator_h__
//exclude SpatialObject
//exclude SpatialObjectTreeContainer
//exclude TreeContainer
#endif //__ExplicitInstantiation_itkPreOrderTreeIterator_h__