#ifndef __ExplicitInstantiation_itkShapedFloodFilledImageFunctionConditionalIterator_h__
#define __ExplicitInstantiation_itkShapedFloodFilledImageFunctionConditionalIterator_h__
//exclude BinaryThresholdImageFunction
#endif //__ExplicitInstantiation_itkShapedFloodFilledImageFunctionConditionalIterator_h__