#ifndef __ExplicitInstantiation_itkShapedFloodFilledFunctionConditionalConstIterator_h__
#define __ExplicitInstantiation_itkShapedFloodFilledFunctionConditionalConstIterator_h__
//exclude BinaryThresholdImageFunction
#endif //__ExplicitInstantiation_itkShapedFloodFilledFunctionConditionalConstIterator_h__