#ifndef __ExplicitInstantiation_itkSymmetricEllipsoidInteriorExteriorSpatialFunction_h__
#define __ExplicitInstantiation_itkSymmetricEllipsoidInteriorExteriorSpatialFunction_h__
extern template class itk::SymmetricEllipsoidInteriorExteriorSpatialFunction<3u, itk::Point<double, 3u> >;
#endif //__ExplicitInstantiation_itkSymmetricEllipsoidInteriorExteriorSpatialFunction_h__