#ifndef __ExplicitInstantiation_itkShapedFloodFilledImageFunctionConditionalConstIterator_h__
#define __ExplicitInstantiation_itkShapedFloodFilledImageFunctionConditionalConstIterator_h__
//exclude BinaryThresholdImageFunction
#endif //__ExplicitInstantiation_itkShapedFloodFilledImageFunctionConditionalConstIterator_h__