#ifndef __ExplicitInstantiation_itkTreeContainer_h__
#define __ExplicitInstantiation_itkTreeContainer_h__
//exclude SpatialObject
//exclude TreeContainer
#endif //__ExplicitInstantiation_itkTreeContainer_h__