#ifndef __ExplicitInstantiation_itkHalfToFullHermitianImageFilter_h__
#define __ExplicitInstantiation_itkHalfToFullHermitianImageFilter_h__
extern template class itk::HalfToFullHermitianImageFilter<itk::Image<std::complex<float>, 2u> >;
#endif //__ExplicitInstantiation_itkHalfToFullHermitianImageFilter_h__