#include "itkRegistrationParameterScalesFromPhysicalShift.h"

template class itk::RegistrationParameterScalesFromPhysicalShift<itk::JointHistogramMutualInformationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >; //Instantiated 4 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double> > >; //Instantiated 8 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::ObjectToObjectMultiMetricv4<2u, 2u, itk::Image<double, 2u>, double> >; //Instantiated 4 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >; //Instantiated 24 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MeanSquaresImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >; //Instantiated 14 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >; //Instantiated 18 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::CorrelationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >; //Instantiated 6 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::JointHistogramMutualInformationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >; //Instantiated 8 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double> > >; //Instantiated 4 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >; //Instantiated 8 times
template class itk::RegistrationParameterScalesFromPhysicalShift<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >; //Instantiated 12 times