#ifndef __ExplicitInstantiation_itkMetaFEMObjectConverter_h__
#define __ExplicitInstantiation_itkMetaFEMObjectConverter_h__
extern template class itk::MetaFEMObjectConverter<2u>;
extern template class itk::MetaFEMObjectConverter<3u>;
#endif //__ExplicitInstantiation_itkMetaFEMObjectConverter_h__