#ifndef __ExplicitInstantiation_itkOnePlusOneEvolutionaryOptimizerv4_h__
#define __ExplicitInstantiation_itkOnePlusOneEvolutionaryOptimizerv4_h__
extern template class itk::OnePlusOneEvolutionaryOptimizerv4<double>;
#endif //__ExplicitInstantiation_itkOnePlusOneEvolutionaryOptimizerv4_h__