#ifndef __ExplicitInstantiation_itkRegistrationParameterScalesFromPhysicalShift_h__
#define __ExplicitInstantiation_itkRegistrationParameterScalesFromPhysicalShift_h__
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::JointHistogramMutualInformationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::ObjectToObjectMultiMetricv4<2u, 2u, itk::Image<double, 2u>, double> >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MeanSquaresImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::CorrelationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::JointHistogramMutualInformationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesFromPhysicalShift<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
#endif //__ExplicitInstantiation_itkRegistrationParameterScalesFromPhysicalShift_h__