#ifndef __ExplicitInstantiation_itkRegistrationParameterScalesEstimator_h__
#define __ExplicitInstantiation_itkRegistrationParameterScalesEstimator_h__
extern template class itk::RegistrationParameterScalesEstimator<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::MeanSquaresImageToImageMetricv4<itk::Image<itk::Vector<double, 3u>, 2u>, itk::Image<itk::Vector<double, 3u>, 2u>, itk::Image<double, 2u>, double, itk::VectorImageToImageMetricTraitsv4<itk::Image<itk::Vector<double, 3u>, 2u>, itk::Image<itk::Vector<double, 3u>, 2u>, itk::Image<double, 2u>, 3u, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<RegistrationParameterScalesFromPhysicalShiftTestMetric<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::JointHistogramMutualInformationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<RegistrationParameterScalesFromPhysicalShiftPointSetTestMetric<itk::PointSet<double, 2u, itk::DefaultStaticMeshTraits<double, 2u, 2u, float, float, double> >, itk::PointSet<double, 2u, itk::DefaultStaticMeshTraits<double, 2u, 2u, float, float, double> > > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::JointHistogramMutualInformationImageToImageMetricv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<RegistrationParameterScalesEstimatorTestMetric<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::EuclideanDistancePointSetToPointSetMetricv4<itk::PointSet<unsigned char, 2u, itk::DefaultStaticMeshTraits<unsigned char, 2u, 2u, float, float, unsigned char> >, itk::PointSet<unsigned char, 2u, itk::DefaultStaticMeshTraits<unsigned char, 2u, 2u, float, float, unsigned char> > > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::ExpectationBasedPointSetToPointSetMetricv4<itk::PointSet<unsigned char, 2u, itk::DefaultStaticMeshTraits<unsigned char, 2u, 2u, float, float, unsigned char> >, itk::PointSet<unsigned char, 2u, itk::DefaultStaticMeshTraits<unsigned char, 2u, 2u, float, float, unsigned char> > > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::MeanSquaresImageToImageMetricv4<itk::Image<itk::Vector<float, 2u>, 2u>, itk::Image<itk::Vector<float, 2u>, 2u>, itk::Image<itk::Vector<float, 2u>, 2u>, double, itk::VectorImageToImageMetricTraitsv4<itk::Image<itk::Vector<float, 2u>, 2u>, itk::Image<itk::Vector<float, 2u>, 2u>, itk::Image<itk::Vector<float, 2u>, 2u>, 2u, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::JointHistogramMutualInformationImageToImageMetricv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::DemonsImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::MattesMutualInformationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::CorrelationImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::ObjectToObjectMultiMetricv4<2u, 2u, itk::Image<double, 2u>, double> >;
extern template class itk::RegistrationParameterScalesEstimator<itk::ImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::JensenHavrdaCharvatTsallisPointSetToPointSetMetricv4<itk::PointSet<unsigned char, 2u, itk::DefaultStaticMeshTraits<unsigned char, 2u, 2u, float, float, unsigned char> > > >;
extern template class itk::RegistrationParameterScalesEstimator<RegistrationParameterScalesFromIndexShiftTestMetric<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::MeanSquaresImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::JointHistogramMutualInformationImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::LabeledPointSetToPointSetMetricv4<itk::PointSet<unsigned int, 2u, itk::DefaultStaticMeshTraits<unsigned int, 2u, 2u, float, float, unsigned int> >, itk::PointSet<unsigned int, 2u, itk::DefaultStaticMeshTraits<unsigned int, 2u, 2u, float, float, unsigned int> > > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::CorrelationImageToImageMetricv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2u>, itk::Image<float, 2u>, itk::Image<float, 2u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::ImageToImageMetricv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 3u>, itk::Image<double, 3u>, itk::Image<double, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<itk::ANTSNeighborhoodCorrelationImageToImageMetricv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u>, double> > >;
extern template class itk::RegistrationParameterScalesEstimator<RegistrationParameterScalesFromJacobianTestMetric<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u> > >;
#endif //__ExplicitInstantiation_itkRegistrationParameterScalesEstimator_h__